/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualclassroom;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sagar
 */
public class PresenterView extends javax.swing.JFrame {

    /**
     * Creates new form PresenterView
     */
    String ipxcc="";
    String userid="";
    public PresenterView(String userid,String ipxcc)
    {
       this.userid=userid;
       this.ipxcc=ipxcc; 
        initComponents();
        setLocationRelativeTo(null);
    }
    private PresenterView() {
       throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jsessionnames = new javax.swing.JComboBox();
        btngotoAgenda = new javax.swing.JButton();
        pnlAgenda = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsessionname = new javax.swing.JTextField();
        txttopic = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnaddtopic = new javax.swing.JButton();
        btnsetAgenda = new javax.swing.JButton();
        btnCleartext = new javax.swing.JButton();
        txtsubtopic = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlCreateAcc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsetUserID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtbranch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtprofession = new javax.swing.JTextField();
        txtspecialist = new javax.swing.JTextField();
        btncreateAcc = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnpic = new javax.swing.JButton();
        lblPic = new javax.swing.JLabel();
        txtsetPassword = new javax.swing.JPasswordField();
        txtconfirmPassword = new javax.swing.JPasswordField();
        jcbaccfor = new javax.swing.JComboBox();
        txturl = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pnlViewDB = new javax.swing.JPanel();
        btnshowPresData = new javax.swing.JButton();
        btnShowParcData = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pnlDelAcc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstdelcan = new javax.swing.JList();
        btndelCandidate = new javax.swing.JButton();
        btnshowDatax = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presenters Job");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        jLabel25.setText("Start Session...");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualclassroom/DeleteAccountimage2.jpg"))); // NOI18N

        jsessionnames.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        btngotoAgenda.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btngotoAgenda.setText("Start Session >>>");
        btngotoAgenda.setToolTipText("Clcik to start session with the preiously set agenda");
        btngotoAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngotoAgendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btngotoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsessionnames, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsessionnames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btngotoAgenda)
                .addGap(18, 18, 18)
                .addComponent(jLabel26))
        );

        jTabbedPane1.addTab("Start Session", jPanel1);

        pnlAgenda.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel15.setText("Session Name");

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel16.setText("Topic");

        txtsessionname.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtsessionname.setToolTipText("<html>New Session to add<br>OR<br>Existing Session to add agenda on");

        txttopic.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txttopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttopicActionPerformed(evt);
            }
        });
        txttopic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttopicFocusLost(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel17.setText("Sub Topic");

        btnaddtopic.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnaddtopic.setText("...");
        btnaddtopic.setToolTipText("Add new sub topic...");
        btnaddtopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtopicActionPerformed(evt);
            }
        });

        btnsetAgenda.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btnsetAgenda.setText("Set");
        btnsetAgenda.setToolTipText("Set agenda");
        btnsetAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsetAgendaActionPerformed(evt);
            }
        });

        btnCleartext.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btnCleartext.setText("Clear");
        btnCleartext.setToolTipText("Clear the fields");
        btnCleartext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleartextActionPerformed(evt);
            }
        });

        txtsubtopic.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtsubtopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtopicActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        jLabel18.setText("Add New Agenda...");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualclassroom/SetAgendaimage.jpg"))); // NOI18N
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlAgendaLayout = new javax.swing.GroupLayout(pnlAgenda);
        pnlAgenda.setLayout(pnlAgendaLayout);
        pnlAgendaLayout.setHorizontalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgendaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsessionname)
                            .addComponent(txttopic)
                            .addGroup(pnlAgendaLayout.createSequentialGroup()
                                .addComponent(txtsubtopic, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(btnaddtopic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlAgendaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgendaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsetAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCleartext, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAgendaLayout.setVerticalGroup(
            pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgendaLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtsessionname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txttopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtsubtopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddtopic))
                .addGap(18, 18, 18)
                .addGroup(pnlAgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCleartext)
                    .addComponent(btnsetAgenda))
                .addGap(66, 66, 66)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab(" Set Agenda", pnlAgenda);

        pnlCreateAcc.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreateAcc.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("General Information");
        pnlCreateAcc.add(jLabel1);
        jLabel1.setBounds(12, 0, 401, 48);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setText("First Name");
        pnlCreateAcc.add(jLabel2);
        jLabel2.setBounds(62, 55, 118, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setText("Last Name");
        pnlCreateAcc.add(jLabel3);
        jLabel3.setBounds(62, 96, 118, 32);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setText("Age");
        pnlCreateAcc.add(jLabel4);
        jLabel4.setBounds(62, 136, 118, 32);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setText("Phone No.");
        pnlCreateAcc.add(jLabel5);
        jLabel5.setBounds(62, 177, 118, 32);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel6.setText("Account for");
        pnlCreateAcc.add(jLabel6);
        jLabel6.setBounds(62, 217, 118, 32);

        txtfname.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtfname);
        txtfname.setBounds(258, 56, 209, 33);

        txtlname.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtlname);
        txtlname.setBounds(258, 96, 209, 33);

        txtage.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtage);
        txtage.setBounds(258, 137, 209, 33);

        txtphone.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtphone);
        txtphone.setBounds(258, 177, 209, 33);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 255));
        jLabel7.setText("User Information");
        pnlCreateAcc.add(jLabel7);
        jLabel7.setBounds(10, 260, 338, 48);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel8.setText("User ID");
        pnlCreateAcc.add(jLabel8);
        jLabel8.setBounds(60, 310, 181, 32);

        txtsetUserID.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtsetUserID);
        txtsetUserID.setBounds(260, 310, 199, 33);

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel9.setText("Password");
        pnlCreateAcc.add(jLabel9);
        jLabel9.setBounds(60, 350, 181, 32);

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel10.setText("Confirm Password");
        pnlCreateAcc.add(jLabel10);
        jLabel10.setBounds(60, 390, 181, 32);

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 255));
        jLabel11.setText("For Presenter/Participant");
        pnlCreateAcc.add(jLabel11);
        jLabel11.setBounds(10, 440, 401, 48);

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel12.setText("Branch");
        pnlCreateAcc.add(jLabel12);
        jLabel12.setBounds(60, 490, 86, 32);

        txtbranch.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtbranch);
        txtbranch.setBounds(150, 490, 162, 33);

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel13.setText("Profession");
        pnlCreateAcc.add(jLabel13);
        jLabel13.setBounds(370, 490, 127, 32);

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel14.setText("Specialist");
        pnlCreateAcc.add(jLabel14);
        jLabel14.setBounds(370, 530, 91, 32);

        txtprofession.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtprofession);
        txtprofession.setBounds(500, 490, 186, 33);

        txtspecialist.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtspecialist);
        txtspecialist.setBounds(500, 530, 186, 33);

        btncreateAcc.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btncreateAcc.setText("Create Account");
        btncreateAcc.setToolTipText("Add new account");
        btncreateAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateAccActionPerformed(evt);
            }
        });
        pnlCreateAcc.add(btncreateAcc);
        btncreateAcc.setBounds(130, 570, 242, 41);

        btnReset.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setToolTipText("Reset fields");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnlCreateAcc.add(btnReset);
        btnReset.setBounds(380, 570, 242, 41);

        btnpic.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        btnpic.setText("Load Picture");
        btnpic.setName("btnpic");
        btnpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpicActionPerformed(evt);
            }
        });
        pnlCreateAcc.add(btnpic);
        btnpic.setBounds(495, 296, 194, 35);

        lblPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblPic.setName("lblpic");
        pnlCreateAcc.add(lblPic);
        lblPic.setBounds(495, 55, 194, 196);

        txtsetPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        pnlCreateAcc.add(txtsetPassword);
        txtsetPassword.setBounds(260, 350, 199, 33);

        txtconfirmPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        txtconfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmPasswordFocusLost(evt);
            }
        });
        pnlCreateAcc.add(txtconfirmPassword);
        txtconfirmPassword.setBounds(260, 390, 199, 33);

        jcbaccfor.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jcbaccfor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Presenter", "Participant" }));
        jcbaccfor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbaccforItemStateChanged(evt);
            }
        });
        pnlCreateAcc.add(jcbaccfor);
        jcbaccfor.setBounds(258, 218, 209, 33);

        txturl.setEditable(false);
        txturl.setMaximumSize(new java.awt.Dimension(6, 22));
        pnlCreateAcc.add(txturl);
        txturl.setBounds(495, 261, 194, 22);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualclassroom/createaccountimage.jpg"))); // NOI18N
        pnlCreateAcc.add(jLabel20);
        jLabel20.setBounds(720, 240, 74, 373);

        jTabbedPane1.addTab("Create Account", pnlCreateAcc);

        pnlViewDB.setBackground(new java.awt.Color(255, 255, 255));

        btnshowPresData.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        btnshowPresData.setText("Presenters Data");
        btnshowPresData.setToolTipText("Click to view Presenters data");
        btnshowPresData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowPresDataActionPerformed(evt);
            }
        });

        btnShowParcData.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        btnShowParcData.setText("Participants Data");
        btnShowParcData.setToolTipText("Clcick to view Participants data");
        btnShowParcData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowParcDataActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        jLabel21.setText("Click To View...");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualclassroom/DeleteAccountimage2.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlViewDBLayout = new javax.swing.GroupLayout(pnlViewDB);
        pnlViewDB.setLayout(pnlViewDBLayout);
        pnlViewDBLayout.setHorizontalGroup(
            pnlViewDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
            .addGroup(pnlViewDBLayout.createSequentialGroup()
                .addGroup(pnlViewDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewDBLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE))
                    .addGroup(pnlViewDBLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(pnlViewDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnShowParcData, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                            .addComponent(btnshowPresData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlViewDBLayout.setVerticalGroup(
            pnlViewDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewDBLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnshowPresData)
                .addGap(18, 18, 18)
                .addComponent(btnShowParcData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel22))
        );

        jTabbedPane1.addTab("View Database", pnlViewDB);

        pnlDelAcc.setBackground(new java.awt.Color(255, 255, 255));
        pnlDelAcc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pnlDelAccFocusGained(evt);
            }
        });

        lstdelcan.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        lstdelcan.setToolTipText("List of available participants");
        jScrollPane1.setViewportView(lstdelcan);

        btndelCandidate.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btndelCandidate.setText("Delete");
        btndelCandidate.setToolTipText("Delets selected participant");
        btndelCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelCandidateActionPerformed(evt);
            }
        });

        btnshowDatax.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        btnshowDatax.setText("Show Data");
        btnshowDatax.setToolTipText("Displays list of all participants");
        btnshowDatax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowDataxActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 72)); // NOI18N
        jLabel23.setText("Select To Delete...");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualclassroom/ViewDataimage2.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlDelAccLayout = new javax.swing.GroupLayout(pnlDelAcc);
        pnlDelAcc.setLayout(pnlDelAccLayout);
        pnlDelAccLayout.setHorizontalGroup(
            pnlDelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDelAccLayout.createSequentialGroup()
                .addGroup(pnlDelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDelAccLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnshowDatax, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDelAccLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDelAccLayout.setVerticalGroup(
            pnlDelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDelAccLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshowDatax)
                    .addComponent(btndelCandidate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24))
        );

        jTabbedPane1.addTab("Delete Account", pnlDelAcc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpicActionPerformed
        // TODO add your handling code here:
String directoryLabel="";
String filenameLabel= "";
String ffile="";
String zfile="";
JFileChooser jf = new JFileChooser();
jf.setFileFilter(new FileNameExtensionFilter("Image Files","jpg","gif","png","bmp"));
  int status = jf.showOpenDialog(null);
if (status == JFileChooser.APPROVE_OPTION) {
File selectedFile = jf.getSelectedFile();
directoryLabel = selectedFile.getParent();
filenameLabel = selectedFile.getName();
ffile = directoryLabel+"/"+filenameLabel;
            try {
                ImageCropperX imgx = new ImageCropperX(ffile,lblPic);
                zfile = imgx.getpath();
                imgx.setVisible(true);
              txturl.setText(zfile);
           // ImageIcon icxx = new ImageIcon(zfile);
            //lblPic.setIcon(icxx);
                
            } catch (IOException ex) {
                Logger.getLogger(PresenterView.class.getName()).log(Level.SEVERE, null, ex);
            }
            
 } else if (status == JFileChooser.CANCEL_OPTION) {
directoryLabel=" ";
filenameLabel= " ";
}  
    }//GEN-LAST:event_btnpicActionPerformed

    private void jcbaccforItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbaccforItemStateChanged
        // TODO add your handling code here:
         if(jcbaccfor.getSelectedItem().equals("Participant"))
         {
        txtprofession.setEnabled(false);
        txtspecialist.setEnabled(false);
         }
         else
         {
        txtprofession.setEnabled(true);
        txtspecialist.setEnabled(true);  
         }
         
    }//GEN-LAST:event_jcbaccforItemStateChanged

    private void btnshowPresDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowPresDataActionPerformed
        // TODO add your handling code here:
     showUserdataForm sudf = new showUserdataForm("Presenter",ipxcc);
     sudf.setVisible(true);
    }//GEN-LAST:event_btnshowPresDataActionPerformed

    private void btnShowParcDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowParcDataActionPerformed
        // TODO add your handling code here:
      showUserdataForm sudf = new showUserdataForm("Participant",ipxcc);
      sudf.setVisible(true);
    }//GEN-LAST:event_btnShowParcDataActionPerformed

    private void btncreateAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateAccActionPerformed
        // TODO add your handling code here:
         String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   String ltp = (String)jcbaccfor.getSelectedItem();
   String fname,lname,accfor,age,phno,usid,paswd,cnfpaswd,branch,profession,specialist;
   //  Database credentials
   FileInputStream fis=null;   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   if(ltp.equals("Participant"))
   {

       try{
                fname=txtfname.getText();
                lname=txtlname.getText();
                age=txtage.getText();
                phno=txtphone.getText();
                usid=txtsetUserID.getText();
                paswd=txtsetPassword.getText();
                cnfpaswd=txtconfirmPassword.getText();
                branch=txtbranch.getText();
                String zem = txturl.getText();
               File file = new File(zem);
               fis = new FileInputStream(file);

                try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               
               //STEP 4: Execute a query
                    stmt = conn.prepareStatement("INSERT INTO partc_info(user_id,first_name,last_name,age,phone,pic) VALUES(?,?,?,?,?,?)");
               stmt.setString(1, usid);
               stmt.setString(2,fname);
               stmt.setString(3, lname);
               stmt.setString(4, age);
               stmt.setString(5, phno);
               stmt.setBinaryStream(6, fis,(int)file.length());
               int x = stmt.executeUpdate();
               JOptionPane.showMessageDialog(null, "Record inserted successfully ");
               
               stmt = conn.prepareStatement("INSERT INTO vct_partc(user_id,passwd) VALUES(?,?)");
               x=0;
               stmt.setString(1,usid);
               stmt.setString(2,paswd);
               x = stmt.executeUpdate();
               
               JOptionPane.showMessageDialog(null, "New user acccount Created Successfully ");
              //STEP 5: Extract data from result set
               

               
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
            }catch(FileNotFoundException ex){
                Logger.getLogger(PresenterView.class.getName()).log(Level.SEVERE, null, ex);
   }//end try
   }
   else if(ltp.equals("Presenter"))
   {
       try{
                fname=txtfname.getText();
                lname=txtlname.getText();
                age=txtage.getText();
                phno=txtphone.getText();
                usid=txtsetUserID.getText();
                paswd=txtsetPassword.getText();
                cnfpaswd=txtconfirmPassword.getText();
                branch=txtbranch.getText();
                profession=txtprofession.getText();
                specialist=txtspecialist.getText();
                String zem = txturl.getText();
               File file = new File(zem);
               fis = new FileInputStream(file);

                try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               
               //STEP 4: Execute a query
                stmt = conn.prepareStatement("INSERT INTO pres_info(user_id,first_name,last_name,age,phone,branch,profession,specialist,pic) VALUES(?,?,?,?,?,?,?,?,?)");
               stmt.setString(1,usid);
               stmt.setString(2,fname);
               stmt.setString(3, lname);
               stmt.setString(4, age);
               stmt.setString(5, phno);
               stmt.setString(6, branch);
               stmt.setString(7,profession);
               stmt.setString(8,specialist);
               stmt.setBinaryStream(9, fis,(int)file.length());
               int x = stmt.executeUpdate();
               JOptionPane.showMessageDialog(null, "Record Inserted Successfully "+x);
              
                stmt = conn.prepareStatement("INSERT INTO vct_pres(user_id,paswd) VALUES(?,?)");
               x=0;
               stmt.setString(1,usid);
               stmt.setString(2,paswd);
               x = stmt.executeUpdate();
               
               JOptionPane.showMessageDialog(null, "New User Acccount Created Successfully ");
              //STEP 5: Extract data from result set
              
               
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
            }catch(FileNotFoundException ex){
                Logger.getLogger(PresenterView.class.getName()).log(Level.SEVERE, null, ex);
   }//end try
   }   
    }//GEN-LAST:event_btncreateAccActionPerformed

    private void txtconfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmPasswordFocusLost
        // TODO add your handling code here:
      if(!txtsetPassword.getText().equals(txtconfirmPassword.getText()))
      {
          JOptionPane.showMessageDialog(null,"Password's don't match, Reenter the Passwords");
          txtsetPassword.setText("");
          txtconfirmPassword.setText("");
      }
    }//GEN-LAST:event_txtconfirmPasswordFocusLost

    private void pnlDelAccFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlDelAccFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDelAccFocusGained

    private void btnshowDataxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowDataxActionPerformed
        // TODO add your handling code here:
               String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   //String ltp = (String)jcbaccfor.getSelectedItem();
   String tname="",fname="",lname="";
   //accfor,age,phno,usid,paswd,cnfpaswd,branch,profession,specialist;
   //  Database credentials
   FileInputStream fis=null;   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               
               //STEP 4: Execute a query
               DefaultListModel dlmod = new DefaultListModel();
             stmt = conn.prepareStatement("SELECT user_id from partc_info");
             ResultSet rs = stmt.executeQuery();
             while(rs.next())
             {
                    tname=rs.getString("user_id");
                    dlmod.addElement(tname);
             }
             lstdelcan.setModel(dlmod);
             rs.close();
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
            
  

    }//GEN-LAST:event_btnshowDataxActionPerformed

    private void btndelCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelCandidateActionPerformed
        // TODO add your handling code here:
        String delitem=(String)lstdelcan.getSelectedValue();
        int delix=lstdelcan.getSelectedIndex();
                     String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   //String ltp = (String)jcbaccfor.getSelectedItem();
   String tname="",fname="",lname="";
   //accfor,age,phno,usid,paswd,cnfpaswd,branch,profession,specialist;
   //  Database credentials
   FileInputStream fis=null;   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
             //  lstdelcan.remove(delix);
               stmt=conn.prepareStatement("DELETE FROM vct_partc WHERE user_id=?");
               stmt.setString(1, delitem);
               int x=stmt.executeUpdate();
               stmt = conn.prepareStatement("DELETE FROM partc_info WHERE user_id=?");
               stmt.setString(1,delitem);
               x = stmt.executeUpdate();
               JOptionPane.showMessageDialog(null,delitem+ " Account Deleted!");
               stmt=conn.prepareStatement("SELECT user_id FROM partc_info");
               DefaultListModel dlmod = new DefaultListModel();

               
               ResultSet rs = stmt.executeQuery();
                while(rs.next())
             {
                    tname=rs.getString("user_id");
                    dlmod.addElement(tname);
             }
             lstdelcan.setModel(dlmod);
              rs.close();
               //STEP 4: Execute a query
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
        
    }//GEN-LAST:event_btndelCandidateActionPerformed

    private void txttopicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttopicFocusLost
        // TODO add your handling code here:
                      String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   //String ltp = (String)jcbaccfor.getSelectedItem();
   String sessionname="",topicname="";
   //accfor,age,phno,usid,paswd,cnfpaswd,branch,profession,specialist;
   //  Database credentials
   sessionname = txtsessionname.getText();
   topicname=txttopic.getText();
   FileInputStream fis=null;   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               
               stmt = conn.prepareStatement("INSERT INTO agenda_tbl(session_name,topic,user_id) VALUES(?,?,?)");
              stmt.setString(1, sessionname);
              stmt.setString(2,topicname);
              stmt.setString(3,userid);
              int x=stmt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Session Set!");
            txtsessionname.setEnabled(false);
            }
            catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
            
    }//GEN-LAST:event_txttopicFocusLost

    private void btnaddtopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtopicActionPerformed
        // TODO add your handling code here:
                    String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   //String ltp = (String)jcbaccfor.getSelectedItem();
   String sessionname="",topicname="",subtopic="";
   //accfor,age,phno,usid,paswd,cnfpaswd,branch,profession,specialist;
   //  Database credentials
   sessionname = txtsessionname.getText();
   topicname=txttopic.getText();
   subtopic=txtsubtopic.getText();
   FileInputStream fis=null;   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               stmt=conn.prepareStatement("select subtopic from agenda_topic where topic=?");
               stmt.setString(1,topicname);
               ResultSet rs=stmt.executeQuery();
               int cnt=0;
               while(rs.next()){
                   if(subtopic.equalsIgnoreCase(rs.getString(1))){
                       cnt++;
                   }
               }
               if(cnt==0){
              stmt = conn.prepareStatement("INSERT INTO agenda_topic(topic,subtopic) VALUES(?,?)");
              stmt.setString(1, topicname);
              stmt.setString(2,subtopic);
              int x=stmt.executeUpdate();
              txtsubtopic.setText("");
              JOptionPane.showMessageDialog(null,"Added to session");
            }
               else{
                   JOptionPane.showMessageDialog(null,"Sub Topic name already exists for the specified topic name\nReenter sub topic whith different name");
                   txtsubtopic.setText("");
               }
            }
               catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try

    }//GEN-LAST:event_btnaddtopicActionPerformed

    private void btnsetAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsetAgendaActionPerformed
        // TODO add your handling code here:

   String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   //String ltp = (String)jcbaccfor.getSelectedItem();
   String sessionname="",topicname="",subtopic="";
   //accfor,age,phno,usid,paswd,cnfpaswd,branch,profession,specialist;
   //  Database credentials
   sessionname = txtsessionname.getText();
   topicname=txttopic.getText();
   subtopic=txtsubtopic.getText();
   FileInputStream fis=null;   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
          Calendar cal = Calendar.getInstance();
	   String str=dateFormat.format(cal.getTime());
              stmt = conn.prepareStatement("INSERT INTO session_tbl(activated,activation_time,session_name) VALUES(?,?,?)");
              stmt.setBoolean(1, false);
              stmt.setString(2,str);
              stmt.setString(3,sessionname);
           int x=stmt.executeUpdate();
           txtsessionname.setText("");
           txtsessionname.setEnabled(true);
           txttopic.setText("");
           txtsubtopic.setText("");
              JOptionPane.showMessageDialog(null, "Session Activated Now");
              
              
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try

    }//GEN-LAST:event_btnsetAgendaActionPerformed

    private void btngotoAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngotoAgendaActionPerformed
        // TODO add your handling code here:
        String session=jsessionnames.getSelectedItem().toString();
        if(session.equals(""))
            JOptionPane.showMessageDialog(null,"Enter Session First...");
        else
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
            String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
            String USER = "root";
             String PASS = "";
             boolean b=false;
             String realnameofsession="";
            Connection conn = null;
            PreparedStatement stmt = null;
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               PreparedStatement st=conn.prepareStatement("select * from agenda_tbl where user_id=?");
               st.setString(1,userid);
               ResultSet rs=st.executeQuery();
               while(rs.next()){
                   if(rs.getString("session_name").equalsIgnoreCase(session)){
                       b=true;
                       realnameofsession=rs.getString("session_name");
                       break;
                   }     
               }
               if(b==true){
                   JOptionPane.showMessageDialog(null,userid+" welcome to session : "+realnameofsession);
                   st=conn.prepareStatement("update session_tbl set activated=? where session_name=?");
                   st.setString(2,session);
                   st.setInt(1,1);
                   st.executeUpdate();
                   dispose();
                   PresenterView2 pcvw = new PresenterView2(userid,ipxcc,realnameofsession);
                pcvw.setVisible(true);
               }
               else{
                  JOptionPane.showMessageDialog(null,session+" session doesnot exist...");
               }
                }
            catch(Exception e)
            {}
        }
               
    }//GEN-LAST:event_btngotoAgendaActionPerformed

    private void btnCleartextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleartextActionPerformed
        // TODO add your handling code here:
        txtsessionname.setText("");
        txttopic.setText("");
        txtsubtopic.setText("");
        txtsessionname.setEditable(true);
    }//GEN-LAST:event_btnCleartextActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtfname.setText("");
        txtlname.setText("");
        txtage.setText("");
        txtphone.setText("");
        txtsetUserID.setText("");
        txtsetPassword.setText("");
        txtconfirmPassword.setText("");
        txtbranch.setText("");
        txtprofession.setText("");
        txtspecialist.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               
               //STEP 4: Execute a query
               javax.swing.DefaultComboBoxModel dlmod = new javax.swing.DefaultComboBoxModel();
             stmt = conn.prepareStatement("SELECT distinct session_name from agenda_tbl where user_id=?");
             stmt.setString(1,userid);
             ResultSet rs = stmt.executeQuery();
             String tname;
             while(rs.next())
             {
                    tname=rs.getString("session_name");
                    dlmod.addElement(tname);
             }
             jsessionnames.setModel(dlmod);
             rs.close();
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
            
    }//GEN-LAST:event_formWindowOpened

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel1MouseEntered

    private void txtsubtopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtopicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtopicActionPerformed

    private void txttopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttopicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttopicActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
         String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
   String DB_URL = "jdbc:mysql://"+ipxcc+":3306/vctuser";
   
   String USER = "root";
   String PASS = "";
   Connection conn = null;
   PreparedStatement stmt = null;
   
            try{
               //STEP 2: Register JDBC driver
                Class.forName(JDBC_DRIVER);
                
               //STEP 3: Open a connection
               System.out.println("Connecting to a selected database...");
               conn = DriverManager.getConnection(DB_URL, USER, PASS);
               System.out.println("Connected database successfully...");
               
               //STEP 4: Execute a query
               javax.swing.DefaultComboBoxModel dlmod = new javax.swing.DefaultComboBoxModel();
             stmt = conn.prepareStatement("SELECT distinct session_name from agenda_tbl where user_id=?");
             stmt.setString(1,userid);
             ResultSet rs = stmt.executeQuery();
             String tname;
             while(rs.next())
             {
                    tname=rs.getString("session_name");
                    dlmod.addElement(tname);
             }
             jsessionnames.setModel(dlmod);
             rs.close();
            }catch(SQLException se){
               //Handle errors for JDBC
               se.printStackTrace();
            }catch(Exception e){
               //Handle errors for Class.forName
               e.printStackTrace();
            }finally{
               //finally block used to close resources
               try{
                  if(stmt!=null)
                     conn.close();
               }catch(SQLException se){
               }// do nothing
               try{
                  if(conn!=null)
                     conn.close();
               }catch(SQLException se){
                  se.printStackTrace();
               }//end finally try
            }//end try
    }//GEN-LAST:event_jPanel1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresenterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PresenterView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleartext;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnShowParcData;
    private javax.swing.JButton btnaddtopic;
    private javax.swing.JButton btncreateAcc;
    private javax.swing.JButton btndelCandidate;
    private javax.swing.JButton btngotoAgenda;
    private javax.swing.JButton btnpic;
    private javax.swing.JButton btnsetAgenda;
    private javax.swing.JButton btnshowDatax;
    private javax.swing.JButton btnshowPresData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox jcbaccfor;
    private javax.swing.JComboBox jsessionnames;
    private javax.swing.JLabel lblPic;
    private javax.swing.JList lstdelcan;
    private javax.swing.JPanel pnlAgenda;
    private javax.swing.JPanel pnlCreateAcc;
    private javax.swing.JPanel pnlDelAcc;
    private javax.swing.JPanel pnlViewDB;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JPasswordField txtconfirmPassword;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtprofession;
    private javax.swing.JTextField txtsessionname;
    private javax.swing.JPasswordField txtsetPassword;
    private javax.swing.JTextField txtsetUserID;
    private javax.swing.JTextField txtspecialist;
    private javax.swing.JTextField txtsubtopic;
    private javax.swing.JTextField txttopic;
    private javax.swing.JTextField txturl;
    // End of variables declaration//GEN-END:variables
}
